# .streamlit/secrets.toml

[connections.snowflake]
account = "xxx"
user = "CHARLESK"
password = "Trial987"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keepalive = true
