# .streamlit/secrets.toml

[connections.snowflake]
account = "FIFDVIU-AC88210"
user = "CKOTTLER"
password = "Trial876"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keepalive = true
