# .streamlit/secrets.toml

[connections.snowflake]
account = "AC88210"
user = "CKOTTLER"
password = "Trial987"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keepalive = true
